@echo off
echo Cleaning up environment...
taskkill /F /IM node.exe /T 2>nul
echo Cleaning up node_modules...
if exist node_modules rmdir /s /q node_modules
if exist package-lock.json del /f /q package-lock.json
echo Installing dependencies...
call npm install --legacy-peer-deps
echo Running Build...
call npm run build
echo Setup complete!
pause
